extends Button


# Declare member variables here. Examples:
# var a = 2

var mapxml = "text"
var mapx = 0
var mapy = 0

# Called when the node enters the scene tree for the first time.
func _ready():
	mapxml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<map>\n  <description/>\n  <name>Unnamed Map</name>\n  <author>Unknown Author</author>\n  <mode>Battalion Map Editor</mode>\n  <rows>15</rows>\n  <cols>10</cols>\n  <layers>3</layers>\n  <palette>\n"
	mapxml = mapxml + "    <entry reference=\"0\">\n      <name>Plains</name>\n      <imageCode>?(plains_v1.png;plains_v2.png;plains_v3.png;plains_v4.png;plains_v5.png;plains_v6.png;plains_v7.png;plains_v8.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1\">\n      <name>Forest</name>\n      <imageCode>?(forest_v1.png;forest_v2.png;forest_v3.png;forest_v4.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"2\">\n      <name>Mountain</name>\n      <imageCode>?(mountains_v1.png;mountains_v2.png;mountains_v3.png;mountains_v4.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"3\">\n      <name>Hill</name>\n      <imageCode>?(hills_v1.png;hills_v2.png;hills_v3.png;hills_v4.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"4\">\n      <name>Depleted Ore Deposit</name>\n      <imageCode>?(depleted_ore_deposit_v1.png;depleted_ore_deposit_v2.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"5\">\n      <name>Enriched Ore Deposit</name>\n      <imageCode>?(enriched_ore_deposit_v1.png;enriched_ore_deposit_v2.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"6\">\n      <name>Ore Deposit</name>\n      <imageCode>?(ore_deposit_v1.png;ore_deposit_v2.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"7\">\n      <name>Wasteland</name>\n      <imageCode>wasteland_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"8\">\n      <name>Volcano</name>\n      <imageCode>volcano_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"11\">\n      <name>Reef</name>\n      <imageCode>?(reef_v1.png;reef_v2.png;reef_v3.png;reef_v4.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"12\">\n      <name>Rock Formation</name>\n      <imageCode>?(rock_formation_v1.png;rock_formation_v2.png;rock_formation_v3.png;rock_formation_v4.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"13\">\n      <name>Desert</name>\n      <imageCode>?(desert_v1.png;desert_v2.png;desert_v3.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"14\">\n      <name>Archipelago</name>\n      <imageCode>?(archipelago_v1.png;archipelago_v2.png;archipelago_v3.png;archipelago_v4.png)</imageCode>\n    </entry>\n"
	
	
	
	
	mapxml = mapxml + "    <entry reference=\"1100\">\n      <name>P1 Strike Commando</name>\n      <imageCode>@(1;strikecommando.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1101\">\n      <name>P1 Heavy Commando</name>\n      <imageCode>@(1;heavycommando.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1102\">\n      <name>P1 Scorpion Tank</name>\n      <imageCode>@(1;scorpiontank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1103\">\n      <name>P1 Lancer Tank</name>\n      <imageCode>@(1;lancer.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1104\">\n      <name>P1 Flak Tank</name>\n      <imageCode>@(1;flak.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1105\">\n      <name>P1 Stealth Tank</name>\n      <imageCode>@(1;stealthtank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1106\">\n      <name>P1 Scorpion Tank</name>\n      <imageCode>@(1;scorpiontank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1107\">\n      <name>P1 Annihilator Tank</name>\n      <imageCode>@(1;annihilatortank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1108\">\n      <name>P1 Mortar Truck</name>\n      <imageCode>@(1;mortartruck.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1109\">\n      <name>P1 Rocket Truck</name>\n      <imageCode>@(1;rockettruck.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1110\">\n      <name>P1 Jammer Truck</name>\n      <imageCode>@(1;jammer.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1111\">\n      <name>P1 Warmachine</name>\n      <imageCode>@(1;warmachine.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1112\">\n      <name>P1 Turret</name>\n      <imageCode>@(1;turret.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1113\">\n      <name>P1 Intrepid</name>\n      <imageCode>@(1;intrepid.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1114\">\n      <name>P1 Corvette</name>\n      <imageCode>@(1;corvette.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1115\">\n      <name>P1 Hunter</name>\n      <imageCode>@(1;hunter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1116\">\n      <name>P1 Battlecruiser</name>\n      <imageCode>@(1;battlecruiser.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1117\">\n      <name>P1 U-Boat</name>\n      <imageCode>@(1;uboat.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1119\">\n      <name>P1 Raptor Fighter</name>\n      <imageCode>@(1;raptorfighter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1120\">\n      <name>P1 Vulture Drone</name>\n      <imageCode>@(1;vulture.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1121\">\n      <name>P1 Condor Bomber</name>\n      <imageCode>@(1;condorbomber.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1123\">\n      <name>P1 Blockade</name>\n      <imageCode>@(1;blockade.png)</imageCode>\n    </entry>\n"
	
	
	mapxml = mapxml + "    <entry reference=\"1200\">\n      <name>P2 Strike Commando</name>\n      <imageCode>@(2;strikecommando.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1201\">\n      <name>P2 Heavy Commando</name>\n      <imageCode>@(2;heavycommando.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1202\">\n      <name>P2 Scorpion Tank</name>\n      <imageCode>@(2;scorpiontank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1203\">\n      <name>P2 Lancer Tank</name>\n      <imageCode>@(2;lancer.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1204\">\n      <name>P2 Flak Tank</name>\n      <imageCode>@(2;flak.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1205\">\n      <name>P2 Stealth Tank</name>\n      <imageCode>@(2;stealthtank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1206\">\n      <name>P2 Scorpion Tank</name>\n      <imageCode>@(2;scorpiontank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1207\">\n      <name>P2 Annihilator Tank</name>\n      <imageCode>@(2;annihilatortank.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1208\">\n      <name>P2 Mortar Truck</name>\n      <imageCode>@(2;mortartruck.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1209\">\n      <name>P2 Rocket Truck</name>\n      <imageCode>@(2;rockettruck.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1210\">\n      <name>P2 Jammer Truck</name>\n      <imageCode>@(2;jammer.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1211\">\n      <name>P2 Warmachine</name>\n      <imageCode>@(2;warmachine.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1212\">\n      <name>P2 Turret</name>\n      <imageCode>@(2;turret.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1213\">\n      <name>P2 Intrepid</name>\n      <imageCode>@(2;intrepid.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1214\">\n      <name>P2 Corvette</name>\n      <imageCode>@(2;corvette.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1215\">\n      <name>P2 Hunter</name>\n      <imageCode>@(2;hunter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1216\">\n      <name>P2 Battlecruiser</name>\n      <imageCode>@(2;battlecruiser.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1217\">\n      <name>P2 U-Boat</name>\n      <imageCode>@(2;uboat.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1219\">\n      <name>P2 Raptor Fighter</name>\n      <imageCode>@(2;raptorfighter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1220\">\n      <name>P2 Vulture Drone</name>\n      <imageCode>@(2;vulture.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1221\">\n      <name>P2 Condor Bomber</name>\n      <imageCode>@(2;condorbomber.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"1223\">\n      <name>P2 Blockade</name>\n      <imageCode>@(2;blockade.png)</imageCode>\n    </entry>\n"
	
	
	
	mapxml = mapxml + "    <entry reference=\"90016\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90017\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90018\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90019\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90020\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90021\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90022\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90023\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90024\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90025\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90026\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90027\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90028\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90029\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90030\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90031\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90048\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90049\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90050\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90051\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90052\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90053\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90054\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90055\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90056\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90057\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90058\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90059\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90060\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90061\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90062\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90063\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90080\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90081\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90082\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90083\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90084\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90085\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90086\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90087\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90088\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90089\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90090\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90091\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90092\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90093\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90094\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90095\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90112\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90113\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90114\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90115\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90116\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90117\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90118\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90119\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90120\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90121\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90122\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90123\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90124\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90125\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90126\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90127\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90144\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90145\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90146\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90147\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90148\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90149\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90150\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90151\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90152\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90153\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90154\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90155\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90156\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90157\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90158\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90159\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90176\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90177\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90178\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90179\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90180\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90181\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90182\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90183\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90184\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90185\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90186\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90187\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90188\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90189\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90190\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90191\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_14_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90208\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90209\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90210\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90211\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90212\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90213\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90214\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90215\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90216\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90217\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90218\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90219\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90220\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90221\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90222\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90223\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90240\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90241\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90242\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90243\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90244\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90245\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90246\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90247\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90248\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90249\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90250\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90251\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90252\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90253\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90254\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90255\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_0_sw.png;sea_13_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90272\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90273\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90274\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90275\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90276\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90277\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90278\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90279\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90280\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90281\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90282\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90283\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90284\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90285\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90286\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90287\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90304\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90305\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90306\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90307\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90308\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90309\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90310\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90311\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90312\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90313\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90314\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90315\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90316\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90317\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90318\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90319\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90336\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90337\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90338\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90339\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90340\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90341\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90342\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90343\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_3_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90344\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90345\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90346\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90347\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90348\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90349\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90350\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90351\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_7_v1.png;sea_4_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90368\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90369\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90370\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90371\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90372\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90373\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90374\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90375\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_3_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90376\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90377\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90378\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90379\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90380\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90381\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90382\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90383\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_7_v1.png;sea_8_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90400\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90401\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90402\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90403\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90404\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90405\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90406\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90407\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90408\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90409\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90410\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90411\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90412\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90413\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90414\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90415\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_14_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90432\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90433\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90434\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90435\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90436\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90437\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90438\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90439\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90440\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90441\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90442\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90443\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90444\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90445\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90446\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90447\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_14_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90464\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90465\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90466\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90467\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90468\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90469\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_2_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90470\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90471\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_11_v1.png;sea_10_v1.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90472\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90473\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90474\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90475\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90476\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90477\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_2_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90478\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90479\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_11_v1.png;sea_0_sw.png;sea_12_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90496\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90497\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90498\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90499\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_15_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90500\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90501\">\n      <name>Sea</name>\n      <imageCode>+(sea_1_v1.png;sea_6_v1.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90502\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90503\">\n      <name>Sea</name>\n      <imageCode>+(sea_9_v1.png;sea_0_ne.png;sea_10_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90504\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90505\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90506\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_15_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90507\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_15_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90508\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90509\">\n      <name>Sea</name>\n      <imageCode>+(sea_5_v1.png;sea_6_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90510\">\n      <name>Sea</name>\n      <imageCode>+(sea_16_v1.png;sea_0_ne.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"90511\">\n      <name>Sea</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	
	mapxml = mapxml + "    <entry reference=\"900\">\n      <name>Neutral Command Center</name>\n      <imageCode>@(0;commandcenter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"901\">\n      <name>Neutral Factory</name>\n      <imageCode>@(0;factory.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"902\">\n      <name>Neutral Oil Refinery</name>\n      <imageCode>@(0;oilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"903\">\n      <name>Neutral Advanced Oil Refinery</name>\n      <imageCode>@(0;advanceoilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"904\">\n      <name>Neutral Oil Rig</name>\n      <imageCode>@(0;oilrig.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"905\">\n      <name>Neutral Sea Control</name>\n      <imageCode>@(0;seacontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"906\">\n      <name>Neutral Ground Control</name>\n      <imageCode>@(0;groundcontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"907\">\n      <name>Neutral Air Control</name>\n      <imageCode>@(0;aircontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"100\">\n      <name>P1 Command Center</name>\n      <imageCode>@(1;commandcenter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"101\">\n      <name>P1 Factory</name>\n      <imageCode>@(1;factory.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"102\">\n      <name>P1 Oil Refinery</name>\n      <imageCode>@(1;oilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"103\">\n      <name>P1 Advanced Oil Refinery</name>\n      <imageCode>@(1;advanceoilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"104\">\n      <name>P1 Oil Rig</name>\n      <imageCode>@(1;oilrig.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"105\">\n      <name>P1 Sea Control</name>\n      <imageCode>@(1;seacontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"106\">\n      <name>P1 Ground Control</name>\n      <imageCode>@(1;groundcontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"107\">\n      <name>P1 Air Control</name>\n      <imageCode>@(1;aircontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"200\">\n      <name>P2 Command Center</name>\n      <imageCode>@(2;commandcenter.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"201\">\n      <name>P2 Factory</name>\n      <imageCode>@(2;factory.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"202\">\n      <name>P2 Oil Refinery</name>\n      <imageCode>@(2;oilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"203\">\n      <name>P2 Advanced Oil Refinery</name>\n      <imageCode>@(2;advanceoilrefinery.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"204\">\n      <name>P2 Oil Rig</name>\n      <imageCode>@(2;oilrig.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"205\">\n      <name>P2 Sea Control</name>\n      <imageCode>@(2;seacontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"206\">\n      <name>P2 Ground Control</name>\n      <imageCode>@(2;groundcontrol.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"207\">\n      <name>P2 Air Control</name>\n      <imageCode>@(2;aircontrol.png)</imageCode>\n    </entry>\n"

	mapxml = mapxml + "    <entry reference=\"80144\">\n      <name>Shore</name>\n      <imageCode>+(shore_10_v1.png;shore_12_v1.png;shore_3_v1.png;shore_5_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80018\">\n      <name>Shore</name>\n      <imageCode>+(shore_4_v1.png;shore_6_v1.png;shore_9_v1.png;shore_11_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80016\">\n      <name>Shore</name>\n      <imageCode>+(shore_10_v1.png;shore_12_v1.png;shore_9_v1.png;shore_11_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80432\">\n      <name>Shore</name>\n      <imageCode>+(shore_10_v1.png;shore_7_v1.png;shore_3_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80438\">\n      <name>Shore</name>\n      <imageCode>+(shore_4_v1.png;sea_0_ne.png;shore_3_v1.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80054\">\n      <name>Shore</name>\n      <imageCode>+(shore_4_v1.png;sea_0_ne.png;shore_9_v1.png;shore_1_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80048\">\n      <name>Shore</name>\n      <imageCode>+(shore_10_v1.png;shore_7_v1.png;shore_9_v1.png;shore_1_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80504\">\n      <name>Shore</name>\n      <imageCode>+(shore_8_v1.png;shore_7_v1.png;sea_0_sw.png;sea_0_se.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80063\">\n      <name>Shore</name>\n      <imageCode>+(sea_0_nw.png;sea_0_ne.png;shore_2_v1.png;shore_1_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80216\">\n      <name>Shore</name>\n      <imageCode>+(shore_8_v1.png;shore_12_v1.png;sea_0_sw.png;shore_5_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80219\">\n      <name>Shore</name>\n      <imageCode>+(sea_0_nw.png;shore_6_v1.png;sea_0_sw.png;shore_5_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80027\">\n      <name>Shore</name>\n      <imageCode>+(sea_0_nw.png;shore_6_v1.png;shore_2_v1.png;shore_11_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"80024\">\n      <name>Shore</name>\n      <imageCode>+(shore_8_v1.png;shore_12_v1.png;shore_2_v1.png;shore_11_v1.png)</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70144\">\n      <name>Road</name>\n      <imageCode>road_13_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70146\">\n      <name>Road</name>\n      <imageCode>road_11_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70018\">\n      <name>Road</name>\n      <imageCode>road_15_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70048\">\n      <name>Road</name>\n      <imageCode>road_12_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70056\">\n      <name>Road</name>\n      <imageCode>road_2_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70024\">\n      <name>Road</name>\n      <imageCode>road_14_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70432\">\n      <name>Road</name>\n      <imageCode>road_5_v1.png</imageCode>\n    </entry>\n"
	
	mapxml = mapxml + "    <entry reference=\"70050\">\n      <name>Road</name>\n      <imageCode>road_6_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70176\">\n      <name>Road</name>\n      <imageCode>road_5_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70054\">\n      <name>Road</name>\n      <imageCode>road_6_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70152\">\n      <name>Road</name>\n      <imageCode>road_3_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70026\">\n      <name>Road</name>\n      <imageCode>road_4_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70216\">\n      <name>Road</name>\n      <imageCode>road_3_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70027\">\n      <name>Road</name>\n      <imageCode>road_4_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70058\">\n      <name>Road</name>\n      <imageCode>road_10_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70062\">\n      <name>Road</name>\n      <imageCode>road_10_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70059\">\n      <name>Road</name>\n      <imageCode>road_10_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70063\">\n      <name>Road</name>\n      <imageCode>road_10_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70184\">\n      <name>Road</name>\n      <imageCode>road_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70504\">\n      <name>Road</name>\n      <imageCode>road_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70440\">\n      <name>Road</name>\n      <imageCode>road_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70248\">\n      <name>Road</name>\n      <imageCode>road_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70434\">\n      <name>Road</name>\n      <imageCode>road_9_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70182\">\n      <name>Road</name>\n      <imageCode>road_9_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70438\">\n      <name>Road</name>\n      <imageCode>road_9_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70178\">\n      <name>Road</name>\n      <imageCode>road_9_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70218\">\n      <name>Road</name>\n      <imageCode>road_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70219\">\n      <name>Road</name>\n      <imageCode>road_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70155\">\n      <name>Road</name>\n      <imageCode>road_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70154\">\n      <name>Road</name>\n      <imageCode>road_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70187\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70190\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70186\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70506\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70510\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70442\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70507\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70191\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70254\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70250\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70251\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70443\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70446\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70511\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70255\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"70447\">\n      <name>Road</name>\n      <imageCode>road_1_v1.png</imageCode>\n    </entry>\n"
	
	
	mapxml = mapxml + "    <entry reference=\"60016\">\n      <name>Bridge</name>\n      <imageCode>bridge_3_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"60048\">\n      <name>Bridge</name>\n      <imageCode>bridge_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"60056\">\n      <name>Bridge</name>\n      <imageCode>bridge_4_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"60024\">\n      <name>Bridge</name>\n      <imageCode>bridge_2_v1.png</imageCode>\n    </entry>\n"
	
	mapxml = mapxml + "    <entry reference=\"50016\">\n      <name>Bridge</name>\n      <imageCode>bridge_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"50144\">\n      <name>Bridge</name>\n      <imageCode>bridge_5_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"50146\">\n      <name>Bridge</name>\n      <imageCode>bridge_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"50018\">\n      <name>Bridge</name>\n      <imageCode>bridge_6_v1.png</imageCode>\n    </entry>\n"
	
	mapxml = mapxml + "    <entry reference=\"40016\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_3_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"40048\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_1_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"40056\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_4_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"40024\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_2_v1.png</imageCode>\n    </entry>\n"
	
	mapxml = mapxml + "    <entry reference=\"30016\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_7_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"30144\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_5_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"30146\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_8_v1.png</imageCode>\n    </entry>\n"
	mapxml = mapxml + "    <entry reference=\"30018\">\n      <name>High Bridge</name>\n      <imageCode>high_bridge_6_v1.png</imageCode>\n    </entry>\n"
	
	
	
	
	
	
	
	
	
	mapxml = mapxml + "  </palette>\n"
	pass # Replace with function body.



# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass

func outprint():
	print("adddaddss")

func gettilenum(y,x) ->int:
	return get_node('..').gettile(y,x)

func gettilemsg(y,x) -> String:
	var tilemsg = ""
	tilemsg = tilemsg + "  <tile c=\"" + str(y) + "\" r=\"" + str(x) + "\">\n"
	if get_node('..').gettile(y,x) != -1:
		tilemsg = tilemsg + "    <layer reference=\"" + str(gettilenum(y,x)) + "\" depth=\"0\"/>\n"
	if get_node('..').get_build(y,x) != -1 or get_node('..').get_build(y,x) == 65535:
		tilemsg = tilemsg + "    <layer reference=\"" + str(get_node('..').get_build(y,x)) + "\" depth=\"1\"/>\n"
	if get_node('..').getmapunit(y,x) != -1:
		tilemsg = tilemsg + "    <layer reference=\"" + str(get_node('..').getmapunit(y,x)) + "\" depth=\"2\"/>\n"
	tilemsg = tilemsg + "  </tile>\n"
	return tilemsg

func _on_output_pressed():
	_ready()
	for mapy in range(10):
		for mapx in range(15):
			#print(get_node('..').gettile(mapy,mapx))
			mapxml = mapxml + gettilemsg(mapy,mapx)
			
	
	mapxml = mapxml + "</map>"
	$text.set_text(mapxml)
	pass # Replace with function body.
